ALTER TABLE TBL_CHR_INFO
DROP CONSTRAINT FK_CHR_INFO_USER_NO;

DROP TABLE TBL_USER_INFO;

CREATE TABLE TBL_USER_INFO
(
    USER_NO    NUMBER NOT NULL,
    USER_GRADE    VARCHAR2(12) DEFAULT '일반회원' NOT NULL,
    USER_ID    VARCHAR2(12) NOT NULL,
    USER_PWD    VARCHAR2(12) NOT NULL,
    USER_NAME    VARCHAR2(20) NOT NULL,
    EMAIL    VARCHAR2(25) NOT NULL,
    USER_STATUS    CHAR(1) DEFAULT 'N' NOT NULL
);

COMMENT ON COLUMN TBL_USER_INFO.USER_NO IS '회원번호';

COMMENT ON COLUMN TBL_USER_INFO.USER_GRADE IS '회원등급';

COMMENT ON COLUMN TBL_USER_INFO.USER_ID IS 'ID';

COMMENT ON COLUMN TBL_USER_INFO.USER_PWD IS 'PWD';

COMMENT ON COLUMN TBL_USER_INFO.USER_NAME IS '이름';

COMMENT ON COLUMN TBL_USER_INFO.EMAIL IS 'EMAIL';

COMMENT ON COLUMN TBL_USER_INFO.USER_STATUS IS '탈퇴여부';

COMMENT ON TABLE TBL_USER_INFO IS '회원정보';

CREATE UNIQUE INDEX 엔터티1_PK1 ON TBL_USER_INFO
( USER_NO );

ALTER TABLE TBL_USER_INFO
 ADD CONSTRAINT PK_USER_NO PRIMARY KEY ( USER_NO )
 USING INDEX 엔터티1_PK1;

ALTER TABLE TBL_USER_INFO
 ADD CONSTRAINT USER_INFO_CK CHECK ( USER_GRADE IN ('관리자', '일반회원') );

ALTER TABLE TBL_USER_INFO
 ADD CONSTRAINT TBL_USER_INFO_CK CHECK ( USER_STATUS IN ('Y', 'N') );

ALTER TABLE TBL_CHR_SKILL
DROP CONSTRAINT FK_CHR_SKILL_CHR_CODE;

ALTER TABLE TBL_CHR_ACH
DROP CONSTRAINT FK_CHR_ACH_CHR_CODE;

ALTER TABLE TBL_CHR_XY_INFO
DROP CONSTRAINT FK_CHR_XY_INFO_CHR_CODE;

ALTER TABLE TBL_CHR_STORY
DROP CONSTRAINT FK_CHR_STORY_CHR_CODE;

ALTER TABLE TBL_INVENTORY
DROP CONSTRAINT FK_INVENTORY_CHR_CODE;

--ALTER TABLE TBL_CHR_INFO
--DROP CONSTRAINT FK_CHR_INFO_USER_NO;

DROP TABLE TBL_CHR_INFO;

CREATE TABLE TBL_CHR_INFO
(
    CHR_CODE    NUMBER NOT NULL,
    USER_NO    NUMBER NOT NULL,
    CHR_NAME    VARCHAR2(20) NOT NULL,
    CHR_HP    NUMBER NOT NULL,
    CHR_MP    NUMBER NOT NULL,
    CHR_EXP    NUMBER NOT NULL,
    CHR_LEVEL    NUMBER NOT NULL,
    CHR_GOLD    NUMBER NOT NULL,
    MAX_HP    NUMBER NOT NULL,
    MAX_MP    NUMBER NOT NULL,
    MAX_EXP    NUMBER NOT NULL,
    CHR_ATT    NUMBER NOT NULL,
    CHR_DEF    NUMBER NOT NULL,
    SFX    CHAR(1) DEFAULT 'Y' NOT NULL,
    BGM    CHAR(1) DEFAULT 'Y' NOT NULL,
    EQUIP_TITLE    VARCHAR2(30),
    EQUIP_WEAPON    VARCHAR2(30) NOT NULL,
    EQUIP_ARMOR    VARCHAR2(30) NOT NULL
);

COMMENT ON COLUMN TBL_CHR_INFO.CHR_CODE IS '캐릭터코드';

COMMENT ON COLUMN TBL_CHR_INFO.USER_NO IS '회원번호';

COMMENT ON COLUMN TBL_CHR_INFO.CHR_NAME IS '캐릭터닉네임';

COMMENT ON COLUMN TBL_CHR_INFO.CHR_HP IS 'HP';

COMMENT ON COLUMN TBL_CHR_INFO.CHR_MP IS 'MP';

COMMENT ON COLUMN TBL_CHR_INFO.CHR_EXP IS 'EXP';

COMMENT ON COLUMN TBL_CHR_INFO.CHR_LEVEL IS '레벨';

COMMENT ON COLUMN TBL_CHR_INFO.CHR_GOLD IS '보유 금액';

COMMENT ON COLUMN TBL_CHR_INFO.MAX_HP IS '최대 HP';

COMMENT ON COLUMN TBL_CHR_INFO.MAX_MP IS '최대 MP';

COMMENT ON COLUMN TBL_CHR_INFO.MAX_EXP IS '최대 EXP';

COMMENT ON COLUMN TBL_CHR_INFO.CHR_ATT IS '캐릭터공격력';

COMMENT ON COLUMN TBL_CHR_INFO.CHR_DEF IS '캐릭터방어력';

COMMENT ON COLUMN TBL_CHR_INFO.SFX IS '효과음';

COMMENT ON COLUMN TBL_CHR_INFO.BGM IS '배경음';

COMMENT ON COLUMN TBL_CHR_INFO.EQUIP_TITLE IS '장착칭호';

COMMENT ON COLUMN TBL_CHR_INFO.EQUIP_WEAPON IS '장착무기';

COMMENT ON COLUMN TBL_CHR_INFO.EQUIP_ARMOR IS '장착방어구';

COMMENT ON TABLE TBL_CHR_INFO IS '캐릭터정보';

CREATE UNIQUE INDEX 엔터티1_PK2 ON TBL_CHR_INFO
( CHR_CODE );

ALTER TABLE TBL_CHR_INFO
 ADD CONSTRAINT PK_CHR_CODE PRIMARY KEY ( CHR_CODE )
 USING INDEX 엔터티1_PK2;

ALTER TABLE TBL_CHR_INFO
 ADD CONSTRAINT FK_CHR_INFO_USER_NO FOREIGN KEY ( USER_NO )
 REFERENCES TBL_USER_INFO (USER_NO );

ALTER TABLE TBL_CHR_INFO
 ADD CONSTRAINT CK_SFX CHECK ( SFX IN ('Y', 'N') );

ALTER TABLE TBL_CHR_INFO
 ADD CONSTRAINT CK_BGM CHECK ( BGM IN ('Y', 'N') );


ALTER TABLE TBL_INVENTORY
DROP CONSTRAINT FK_INVENTORY_ITEM_CODE;

DROP TABLE TBL_ITEM_LIST;

CREATE TABLE TBL_ITEM_LIST
(
    ITEM_CODE    NUMBER NOT NULL,
    ITEM_CATEGORY    VARCHAR2(12) NOT NULL,
    ITEM_NAME    VARCHAR2(20) NOT NULL,
    ITEM_PRICE    NUMBER NOT NULL,
    ITEM_STATS    NUMBER,
    ITEM_SCRIPT    VARCHAR2(150) NOT NULL
);

COMMENT ON COLUMN TBL_ITEM_LIST.ITEM_CODE IS '아이템코드';

COMMENT ON COLUMN TBL_ITEM_LIST.ITEM_CATEGORY IS '아이템종류';

COMMENT ON COLUMN TBL_ITEM_LIST.ITEM_NAME IS '아이템명';

COMMENT ON COLUMN TBL_ITEM_LIST.ITEM_PRICE IS '가격';

COMMENT ON COLUMN TBL_ITEM_LIST.ITEM_STATS IS '아이템능력치';

COMMENT ON COLUMN TBL_ITEM_LIST.ITEM_SCRIPT IS '설명';

COMMENT ON TABLE TBL_ITEM_LIST IS '아이템정보';

CREATE UNIQUE INDEX 엔터티1_PK3 ON TBL_ITEM_LIST
( ITEM_CODE );

ALTER TABLE TBL_ITEM_LIST
 ADD CONSTRAINT PK_ITEM_CODE PRIMARY KEY ( ITEM_CODE )
 USING INDEX 엔터티1_PK3;

ALTER TABLE TBL_ITEM_LIST
 ADD CONSTRAINT CK_ITEM_CATEGORY CHECK ( ITEM_CATEGORY IN ('무기', '방어구', 'HP물약', 'MP물약', '기타') );


--ALTER TABLE TBL_INVENTORY
--DROP CONSTRAINT FK_INVENTORY_CHR_CODE;

--ALTER TABLE TBL_INVENTORY
--DROP CONSTRAINT FK_INVENTORY_ITEM_CODE;

DROP TABLE TBL_INVENTORY;

CREATE TABLE TBL_INVENTORY
(
    CHR_CODE    NUMBER NOT NULL,
    INVEN_CATEGORY    VARCHAR2(12) NOT NULL,
    INVEN_ID    NUMBER NOT NULL,
    ITEM_CODE    NUMBER NOT NULL
);

COMMENT ON COLUMN TBL_INVENTORY.CHR_CODE IS '캐릭터코드';

COMMENT ON COLUMN TBL_INVENTORY.INVEN_CATEGORY IS '카테고리명';

COMMENT ON COLUMN TBL_INVENTORY.INVEN_ID IS '인벤토리ID';

COMMENT ON COLUMN TBL_INVENTORY.ITEM_CODE IS '아이템코드';

COMMENT ON TABLE TBL_INVENTORY IS '인벤토리';

CREATE UNIQUE INDEX 엔터티1_PK4 ON TBL_INVENTORY
( CHR_CODE, INVEN_ID, INVEN_CATEGORY );

ALTER TABLE TBL_INVENTORY
 ADD CONSTRAINT PK_COMP_CHR_CODE_INVEN_ID_CTG PRIMARY KEY ( CHR_CODE, INVEN_ID, INVEN_CATEGORY )
 USING INDEX 엔터티1_PK4;

ALTER TABLE TBL_INVENTORY
 ADD CONSTRAINT FK_INVENTORY_CHR_CODE FOREIGN KEY ( CHR_CODE )
 REFERENCES TBL_CHR_INFO (CHR_CODE );

ALTER TABLE TBL_INVENTORY
 ADD CONSTRAINT FK_INVENTORY_ITEM_CODE FOREIGN KEY ( ITEM_CODE )
 REFERENCES TBL_ITEM_LIST (ITEM_CODE );


ALTER TABLE TBL_CHR_SKILL
DROP CONSTRAINT FK_CHR_SKILL_SKILL_CODE;

DROP TABLE TBL_SKILL_LIST;

CREATE TABLE TBL_SKILL_LIST
(
    SKILL_CODE    NUMBER NOT NULL,
    SKILL_NAME    VARCHAR2(20) NOT NULL,
    SKILL_ATT    NUMBER NOT NULL,
    MP_CONSUM    NUMBER NOT NULL,
    SKILL_OPEN_LV    NUMBER NOT NULL,
    SKILL_SCRIPT    VARCHAR2(150) NOT NULL
);

COMMENT ON COLUMN TBL_SKILL_LIST.SKILL_CODE IS '스킬코드';

COMMENT ON COLUMN TBL_SKILL_LIST.SKILL_NAME IS '스킬명';

COMMENT ON COLUMN TBL_SKILL_LIST.SKILL_ATT IS '스킬공격력';

COMMENT ON COLUMN TBL_SKILL_LIST.MP_CONSUM IS '스킬MP소모량';

COMMENT ON COLUMN TBL_SKILL_LIST.SKILL_OPEN_LV IS '스킬개방레벨';

COMMENT ON COLUMN TBL_SKILL_LIST.SKILL_SCRIPT IS '스킬설명';

COMMENT ON TABLE TBL_SKILL_LIST IS '스킬정보';

CREATE UNIQUE INDEX 엔터티1_PK5 ON TBL_SKILL_LIST
( SKILL_CODE );

ALTER TABLE TBL_SKILL_LIST
 ADD CONSTRAINT PK_SKILL_CODE PRIMARY KEY ( SKILL_CODE )
 USING INDEX 엔터티1_PK5;


--ALTER TABLE TBL_CHR_SKILL
--DROP CONSTRAINT FK_CHR_SKILL_CHR_CODE;

--ALTER TABLE TBL_CHR_SKILL
--DROP CONSTRAINT FK_CHR_SKILL_SKILL_CODE;

DROP TABLE TBL_CHR_SKILL;

CREATE TABLE TBL_CHR_SKILL
(
    CHR_CODE    NUMBER NOT NULL,
    SKILL_CODE    NUMBER NOT NULL
);

COMMENT ON COLUMN TBL_CHR_SKILL.CHR_CODE IS '캐릭터코드';

COMMENT ON COLUMN TBL_CHR_SKILL.SKILL_CODE IS '스킬코드';

COMMENT ON TABLE TBL_CHR_SKILL IS '스킬보유목록';

CREATE UNIQUE INDEX 엔터티1_PK6 ON TBL_CHR_SKILL
( CHR_CODE, SKILL_CODE );

ALTER TABLE TBL_CHR_SKILL
 ADD CONSTRAINT PK_COMP_CHR_SKILL_CODE PRIMARY KEY ( CHR_CODE, SKILL_CODE )
 USING INDEX 엔터티1_PK6;

ALTER TABLE TBL_CHR_SKILL
 ADD CONSTRAINT FK_CHR_SKILL_CHR_CODE FOREIGN KEY ( CHR_CODE )
 REFERENCES TBL_CHR_INFO (CHR_CODE );

ALTER TABLE TBL_CHR_SKILL
 ADD CONSTRAINT FK_CHR_SKILL_SKILL_CODE FOREIGN KEY ( SKILL_CODE )
 REFERENCES TBL_SKILL_LIST (SKILL_CODE );


ALTER TABLE TBL_CHR_ACH
DROP CONSTRAINT FK_CHR_ACH_ACH_CODE;

DROP TABLE TBL_ACH_LIST;

CREATE TABLE TBL_ACH_LIST
(
    ACH_CODE    NUMBER NOT NULL,
    ACH_NAME    VARCHAR2(20) NOT NULL,
    ACH_CLR_SCRIPT    VARCHAR2(150) NOT NULL,
    ACH_CLR_CONDITION    NUMBER NOT NULL
);

COMMENT ON COLUMN TBL_ACH_LIST.ACH_CODE IS '업적코드';

COMMENT ON COLUMN TBL_ACH_LIST.ACH_NAME IS '업적명';

COMMENT ON COLUMN TBL_ACH_LIST.ACH_CLR_SCRIPT IS '달성조건내용';

COMMENT ON COLUMN TBL_ACH_LIST.ACH_CLR_CONDITION IS '업적달성조건';

COMMENT ON TABLE TBL_ACH_LIST IS '업적';

CREATE UNIQUE INDEX 엔터티1_PK7 ON TBL_ACH_LIST
( ACH_CODE );

ALTER TABLE TBL_ACH_LIST
 ADD CONSTRAINT PK_ACH_CODE PRIMARY KEY ( ACH_CODE )
 USING INDEX 엔터티1_PK7;


--ALTER TABLE TBL_CHR_ACH
--DROP CONSTRAINT FK_CHR_ACH_ACH_CODE;

--ALTER TABLE TBL_CHR_ACH
--DROP CONSTRAINT FK_CHR_ACH_CHR_CODE;

DROP TABLE TBL_CHR_ACH;

CREATE TABLE TBL_CHR_ACH
(
    CHR_CODE    NUMBER NOT NULL,
    ACH_CODE    NUMBER NOT NULL,
    ACH_PROGRESS    NUMBER NOT NULL
);

COMMENT ON COLUMN TBL_CHR_ACH.CHR_CODE IS '캐릭터코드';

COMMENT ON COLUMN TBL_CHR_ACH.ACH_CODE IS '업적코드';

COMMENT ON COLUMN TBL_CHR_ACH.ACH_PROGRESS IS '업적진행현황';

COMMENT ON TABLE TBL_CHR_ACH IS '업적보유목록';

CREATE UNIQUE INDEX 엔터티1_PK8 ON TBL_CHR_ACH
( CHR_CODE, ACH_CODE );

ALTER TABLE TBL_CHR_ACH
 ADD CONSTRAINT PK_COMP_ACH_CHR_CODE PRIMARY KEY ( CHR_CODE, ACH_CODE )
 USING INDEX 엔터티1_PK8;

ALTER TABLE TBL_CHR_ACH
 ADD CONSTRAINT FK_CHR_ACH_ACH_CODE FOREIGN KEY ( ACH_CODE )
 REFERENCES TBL_ACH_LIST (ACH_CODE );

ALTER TABLE TBL_CHR_ACH
 ADD CONSTRAINT FK_CHR_ACH_CHR_CODE FOREIGN KEY ( CHR_CODE )
 REFERENCES TBL_CHR_INFO (CHR_CODE );


DROP TABLE TBL_STORY_LIST;

CREATE TABLE TBL_STORY_LIST
(
    STORY_CODE    NUMBER NOT NULL,
    CHAP_TITLE    VARCHAR2(20) NOT NULL,
    CHAP_SCRIPT    VARCHAR2(150) NOT NULL
);

COMMENT ON COLUMN TBL_STORY_LIST.STORY_CODE IS '스토리코드';

COMMENT ON COLUMN TBL_STORY_LIST.CHAP_TITLE IS '스토리명';

COMMENT ON COLUMN TBL_STORY_LIST.CHAP_SCRIPT IS '스토리내용';

COMMENT ON TABLE TBL_STORY_LIST IS '게임스토리';

CREATE UNIQUE INDEX 엔터티1_PK9 ON TBL_STORY_LIST
( STORY_CODE );

ALTER TABLE TBL_STORY_LIST
 ADD CONSTRAINT PK_STORY_CODE PRIMARY KEY ( STORY_CODE )
 USING INDEX 엔터티1_PK9;


--ALTER TABLE TBL_CHR_STORY
--DROP CONSTRAINT FK_CHR_STORY_CHR_CODE;

DROP TABLE TBL_CHR_STORY;

CREATE TABLE TBL_CHR_STORY
(
    CHR_CODE    NUMBER NOT NULL,
    STORY_CODE    NUMBER NOT NULL
);

COMMENT ON COLUMN TBL_CHR_STORY.CHR_CODE IS '캐릭터코드';

COMMENT ON COLUMN TBL_CHR_STORY.STORY_CODE IS '스토리코드';

COMMENT ON TABLE TBL_CHR_STORY IS '캐릭터챕터정보';

CREATE UNIQUE INDEX 엔터티1_PK10 ON TBL_CHR_STORY
( CHR_CODE, STORY_CODE );

ALTER TABLE TBL_CHR_STORY
 ADD CONSTRAINT PK_COMP_CHR_STORY_CODE PRIMARY KEY ( CHR_CODE, STORY_CODE )
 USING INDEX 엔터티1_PK10;

ALTER TABLE TBL_CHR_STORY
 ADD CONSTRAINT FK_CHR_STORY_CHR_CODE FOREIGN KEY ( CHR_CODE )
 REFERENCES TBL_CHR_INFO (CHR_CODE );


ALTER TABLE TBL_MON_IN_MAP
DROP CONSTRAINT FK_MON_IN_MAP_MON_CODE;

DROP TABLE TBL_MON_INFO;

CREATE TABLE TBL_MON_INFO
(
    MON_CODE    NUMBER NOT NULL,
    MON_NAME    VARCHAR2(20) NOT NULL,
    MON_HP    NUMBER NOT NULL,
    MON_ATT    NUMBER NOT NULL,
    MON_SKILL_ATT    NUMBER,
    MON_DEF    NUMBER NOT NULL,
    MON_EXP    NUMBER NOT NULL,
    DROP_GOLD    NUMBER NOT NULL
);

COMMENT ON COLUMN TBL_MON_INFO.MON_CODE IS '몬스터코드';

COMMENT ON COLUMN TBL_MON_INFO.MON_NAME IS '몬스터이름';

COMMENT ON COLUMN TBL_MON_INFO.MON_HP IS '몬스터HP';

COMMENT ON COLUMN TBL_MON_INFO.MON_ATT IS '몬스터공격력';

COMMENT ON COLUMN TBL_MON_INFO.MON_SKILL_ATT IS '몬스터스킬공격력';

COMMENT ON COLUMN TBL_MON_INFO.MON_DEF IS '몬스터방어력';

COMMENT ON COLUMN TBL_MON_INFO.MON_EXP IS '몬스터경험치';

COMMENT ON COLUMN TBL_MON_INFO.DROP_GOLD IS '몬스터골드량';

COMMENT ON TABLE TBL_MON_INFO IS '몬스터정보';

CREATE UNIQUE INDEX 엔터티1_PK11 ON TBL_MON_INFO
( MON_CODE );

ALTER TABLE TBL_MON_INFO
 ADD CONSTRAINT PK_MON_CODE PRIMARY KEY ( MON_CODE )
 USING INDEX 엔터티1_PK11;


ALTER TABLE TBL_CHR_XY_INFO
DROP CONSTRAINT FK_CHR_XY_INFO_MAP_CODE;

ALTER TABLE TBL_MON_IN_MAP
DROP CONSTRAINT FK_MON_IN_MAP_MAP_CODE;

DROP TABLE TBL_MAP;

CREATE TABLE TBL_MAP
(
    MAP_CODE    NUMBER NOT NULL,
    MAP_NAME    VARCHAR2(20) NOT NULL
);

COMMENT ON COLUMN TBL_MAP.MAP_CODE IS 'Map코드';

COMMENT ON COLUMN TBL_MAP.MAP_NAME IS 'Map이름';

COMMENT ON TABLE TBL_MAP IS '맵';

CREATE UNIQUE INDEX 엔터티1_PK12 ON TBL_MAP
( MAP_CODE );

ALTER TABLE TBL_MAP
 ADD CONSTRAINT PK_MAP_CODE PRIMARY KEY ( MAP_CODE )
 USING INDEX 엔터티1_PK12;


--ALTER TABLE TBL_MON_IN_MAP
--DROP CONSTRAINT FK_MON_IN_MAP_MAP_CODE;

--ALTER TABLE TBL_MON_IN_MAP
--DROP CONSTRAINT FK_MON_IN_MAP_MON_CODE;

DROP TABLE TBL_MON_IN_MAP;

CREATE TABLE TBL_MON_IN_MAP
(
    MAP_CODE    NUMBER NOT NULL,
    MON_CODE    NUMBER NOT NULL,
    RND_APPEAR    NUMBER NOT NULL
);

COMMENT ON COLUMN TBL_MON_IN_MAP.MAP_CODE IS 'Map코드';

COMMENT ON COLUMN TBL_MON_IN_MAP.MON_CODE IS '몬스터코드';

COMMENT ON COLUMN TBL_MON_IN_MAP.RND_APPEAR IS '전투몬스터등장확률';

COMMENT ON TABLE TBL_MON_IN_MAP IS '맵별몬스터등장정보';

CREATE UNIQUE INDEX 엔터티1_PK13 ON TBL_MON_IN_MAP
( MAP_CODE, MON_CODE );

ALTER TABLE TBL_MON_IN_MAP
 ADD CONSTRAINT PK_COMP_MAP_MON_CODE PRIMARY KEY ( MAP_CODE, MON_CODE )
 USING INDEX 엔터티1_PK13;

ALTER TABLE TBL_MON_IN_MAP
 ADD CONSTRAINT FK_MON_IN_MAP_MAP_CODE FOREIGN KEY ( MAP_CODE )
 REFERENCES TBL_MAP (MAP_CODE );

ALTER TABLE TBL_MON_IN_MAP
 ADD CONSTRAINT FK_MON_IN_MAP_MON_CODE FOREIGN KEY ( MON_CODE )
 REFERENCES TBL_MON_INFO (MON_CODE );


--ALTER TABLE TBL_CHR_XY_INFO
--DROP CONSTRAINT FK_CHR_XY_INFO_CHR_CODE;

--ALTER TABLE TBL_CHR_XY_INFO
--DROP CONSTRAINT FK_CHR_XY_INFO_MAP_CODE;

DROP TABLE TBL_CHR_XY_INFO;

CREATE TABLE TBL_CHR_XY_INFO
(
    CHR_CODE    NUMBER NOT NULL,
    MAP_CODE    NUMBER NOT NULL,
    CHR_XY    VARCHAR2(10) NOT NULL
);

COMMENT ON COLUMN TBL_CHR_XY_INFO.CHR_CODE IS '캐릭터코드';

COMMENT ON COLUMN TBL_CHR_XY_INFO.MAP_CODE IS 'Map코드';

COMMENT ON COLUMN TBL_CHR_XY_INFO.CHR_XY IS '캐릭터좌표정보';

COMMENT ON TABLE TBL_CHR_XY_INFO IS '캐릭터위치정보';

CREATE UNIQUE INDEX 엔터티1_PK14 ON TBL_CHR_XY_INFO
( CHR_CODE, MAP_CODE );

ALTER TABLE TBL_CHR_XY_INFO
 ADD CONSTRAINT PK_COMP_CHR_MAP_CODE PRIMARY KEY ( CHR_CODE, MAP_CODE )
 USING INDEX 엔터티1_PK14;

ALTER TABLE TBL_CHR_XY_INFO
 ADD CONSTRAINT FK_CHR_XY_INFO_CHR_CODE FOREIGN KEY ( CHR_CODE )
 REFERENCES TBL_CHR_INFO (CHR_CODE );

ALTER TABLE TBL_CHR_XY_INFO
 ADD CONSTRAINT FK_CHR_XY_INFO_MAP_CODE FOREIGN KEY ( MAP_CODE )
 REFERENCES TBL_MAP (MAP_CODE );


DROP TABLE TBL_IMAGE;

CREATE TABLE TBL_IMAGE
(
    IMG_ID    NUMBER NOT NULL,
    IMG_CATEGORY    VARCHAR2(30) NOT NULL,
    IMG_NAME    VARCHAR2(30) NOT NULL,
    IMG_ADDRESS    VARCHAR2(100) NOT NULL
);

COMMENT ON COLUMN TBL_IMAGE.IMG_ID IS '이미지ID';

COMMENT ON COLUMN TBL_IMAGE.IMG_CATEGORY IS '이미지분류';

COMMENT ON COLUMN TBL_IMAGE.IMG_NAME IS '이미지이름';

COMMENT ON COLUMN TBL_IMAGE.IMG_ADDRESS IS '이미지주소';

COMMENT ON TABLE TBL_IMAGE IS '이미지';

CREATE UNIQUE INDEX 엔터티1_PK15 ON TBL_IMAGE
( IMG_ID );

ALTER TABLE TBL_IMAGE
 ADD CONSTRAINT PK_IMG_ID PRIMARY KEY ( IMG_ID )
 USING INDEX 엔터티1_PK15;

ALTER TABLE TBL_IMAGE
 ADD CONSTRAINT TBL_IMAGE_CK CHECK ( IMG_CATEGORY IN ('인물', '배경', '아이템', '스킬', '기타') );


DROP TABLE TBL_SOUND;

CREATE TABLE TBL_SOUND
(
    SND_ID    NUMBER NOT NULL,
    SND_CATEGORY    VARCHAR2(30) NOT NULL,
    SND_NAME    VARCHAR2(30) NOT NULL,
    SND_ADDRESS    VARCHAR2(100) NOT NULL
);

COMMENT ON COLUMN TBL_SOUND.SND_ID IS '음향ID';

COMMENT ON COLUMN TBL_SOUND.SND_CATEGORY IS '음향분류';

COMMENT ON COLUMN TBL_SOUND.SND_NAME IS '음향이름';

COMMENT ON COLUMN TBL_SOUND.SND_ADDRESS IS '음향주소';

COMMENT ON TABLE TBL_SOUND IS '음향효과';

CREATE UNIQUE INDEX 엔터티1_PK16 ON TBL_SOUND
( SND_ID );

ALTER TABLE TBL_SOUND
 ADD CONSTRAINT PK_SND_ID PRIMARY KEY ( SND_ID )
 USING INDEX 엔터티1_PK16;

ALTER TABLE TBL_SOUND
 ADD CONSTRAINT TBL_SOUND_CK CHECK ( SND_CATEGORY IN ('효과음', '배경음') );
 
/* 관리자 및 일반회원 입력 */
INSERT
  INTO TBL_USER_INFO
(
  USER_NO
, USER_GRADE
, USER_ID
, USER_PWD
, USER_NAME
, EMAIL
, USER_STATUS
)
VALUES
(
  1
, '관리자'
, 'ADMIN'
, 'ADMIN'
, '구권박정조'
, 'kkpjj@greedy.com'
, 'N'
);

INSERT
  INTO TBL_USER_INFO
(
  USER_NO
, USER_GRADE
, USER_ID
, USER_PWD
, USER_NAME
, EMAIL
, USER_STATUS
)
VALUES
(
  2
, '일반회원'
, 'USER01'
, 'PASS01'
, '구권박정조'
, 'kkpjj@greedy.com'
, 'N'
);

/* 아이템 입력 */
INSERT
  INTO TBL_CHR_INFO
(
  CHR_CODE
, USER_NO
, CHR_NAME
, CHR_HP
, CHR_MP
, CHR_EXP
, CHR_LEVEL
, CHR_GOLD
, MAX_HP
, MAX_MP
, MAX_EXP
, CHR_ATT
, CHR_DEF
, SFX
, BGM
, EQUIP_TITLE
, EQUIP_WEAPON
, EQUIP_ARMOR
)
VALUES
(
  1
, 2
, 'TEST'
, 100
, 50
, 100
, 1
, 1000
, 100
, 50
, 100
, 10
, 10
, 'N'
, 'N'
, NULL
, '주먹'
, '허름한 잠옷'
);

INSERT
  INTO TBL_ITEM_LIST
(
  ITEM_CODE
, ITEM_CATEGORY
, ITEM_NAME
, ITEM_PRICE
, ITEM_STATS
, ITEM_SCRIPT
)
VALUES
(
  1
, '무기'
, '주먹'
, 0
, 0
, '물주먹이다'
);

INSERT
  INTO TBL_ITEM_LIST
(
  ITEM_CODE
, ITEM_CATEGORY
, ITEM_NAME
, ITEM_PRICE
, ITEM_STATS
, ITEM_SCRIPT
)
VALUES
(
  2
, '방어구'
, '허름한 잠옷'
, 0
, 0
, '맨몸 가리개'
);

INSERT
  INTO TBL_ITEM_LIST
(
  ITEM_CODE
, ITEM_CATEGORY
, ITEM_NAME
, ITEM_PRICE
, ITEM_STATS
, ITEM_SCRIPT
)
VALUES
(
  3
, '무기'
, '화염의 카타나'
, 500
, 100
, '화염에 휩싸인 메이플스토리에서 가져온 무기'
);


INSERT
  INTO TBL_ITEM_LIST
(
  ITEM_CODE
, ITEM_CATEGORY
, ITEM_NAME
, ITEM_PRICE
, ITEM_STATS
, ITEM_SCRIPT
)
VALUES
(
  4
, '방어구'
, '대자연의 힘'
, 500
, 40
, '리그오브레전드의 공수한 아이템'
);


INSERT
  INTO TBL_ITEM_LIST
(
  ITEM_CODE
, ITEM_CATEGORY
, ITEM_NAME
, ITEM_PRICE
, ITEM_STATS
, ITEM_SCRIPT
)
VALUES
(
  5
, 'HP물약'
, '빨간포션'
, 50
, 50
, '맛없는 빨간 물약'
);


INSERT
  INTO TBL_ITEM_LIST
(
  ITEM_CODE
, ITEM_CATEGORY
, ITEM_NAME
, ITEM_PRICE
, ITEM_STATS
, ITEM_SCRIPT
)
VALUES
(
  6
, 'MP물약'
, '파란포션'
, 50
, 50
, '맛있어보이지만 맛없는 파란 물약'
);

/* 스킬 입력 */
INSERT
  INTO TBL_SKILL_LIST
(
  SKILL_CODE
, SKILL_NAME
, SKILL_ATT
, MP_CONSUM
, SKILL_OPEN_LV
, SKILL_SCRIPT
)
VALUES
(
  1
, '정권찌르기'
, 0.2
, 20
, 1
, '단숨에 적의 급소를 공격하는 정권찌르기'
);

INSERT
  INTO TBL_SKILL_LIST
(
  SKILL_CODE
, SKILL_NAME
, SKILL_ATT
, MP_CONSUM
, SKILL_OPEN_LV
, SKILL_SCRIPT
)
VALUES
(
  2
, '쾌도난마'
, 0.5
, 50
, 5
, '어디선가 들어본 듯한 강력해 보이는 스킬'
);


/* 업적 및 칭호 입력 */
INSERT
  INTO TBL_ACH_LIST
(
  ACH_CODE
, ACH_NAME
, ACH_CLR_SCRIPT
, ACH_CLR_CONDITION
)
VALUES
(
  1
, '토끼 학살자'
, '토끼'
, 1000
);

INSERT
  INTO TBL_ACH_LIST
(
  ACH_CODE
, ACH_NAME
, ACH_CLR_SCRIPT
, ACH_CLR_CONDITION
)
VALUES
(
  2
, '호랑이 학살자'
, '호랑이'
, 1000
);

/* 게임스토리 입력 */
INSERT
  INTO TBL_STORY_LIST
(
  STORY_CODE
, CHAP_TITLE
, CHAP_SCRIPT
)
VALUES
(
  1
, '오프닝'
, '평화롭게 지내던 어느 날...'
);

INSERT
  INTO TBL_STORY_LIST
(
  STORY_CODE
, CHAP_TITLE
, CHAP_SCRIPT
)
VALUES
(
  2
, '오프닝'
, '갑자기 자라클 세력이 침입하여 가족을 끌고 갔다.'
);

/* 몬스터 입력 */
INSERT
  INTO TBL_MON_INFO
(
  MON_CODE
, MON_NAME
, MON_HP
, MON_ATT
, MON_SKILL_ATT
, MON_DEF
, MON_EXP
, DROP_GOLD
)
VALUES
(
  1
, '빨간슬라임'
, 50
, 10
, 0
, 10
, 20
, 25
);

INSERT
  INTO TBL_MON_INFO
(
  MON_CODE
, MON_NAME
, MON_HP
, MON_ATT
, MON_SKILL_ATT
, MON_DEF
, MON_EXP
, DROP_GOLD
)
VALUES
(
  2
, '노란슬라임'
, 60
, 15
, 0
, 15
, 25
, 30
);

INSERT
  INTO TBL_MON_INFO
(
  MON_CODE
, MON_NAME
, MON_HP
, MON_ATT
, MON_SKILL_ATT
, MON_DEF
, MON_EXP
, DROP_GOLD
)
VALUES
(
  3
, '야스요네'
, 500
, 100
, 0.5
, 50
, 200
, 500
);


/* 맵 입력 */
INSERT
  INTO TBL_MAP
(
  MAP_CODE
, MAP_NAME
)
VALUES
(
  1
, '마을'
);

INSERT
  INTO TBL_MAP
(
  MAP_CODE
, MAP_NAME
)
VALUES
(
  2
, '필드1'
);

COMMIT;
